### ISSUE TITLE
TypeError: execa.command is not a function

### ISSUE THREAD

**Issue by rrfheff** [sindresorhus/execa#428]
version: 4.0.2

**Comment by rrfheff** [comment]
it works in 4.0.0
code: 
const execa = require('execa')
execa.command(`npm i`)
