### ISSUE TITLE
Correct tsc options to prevent TS2834 error?

### ISSUE THREAD

**Issue by arlac77** [sindresorhus/execa#1031]
After upgrading to v9.0.0 I have some difficulties to set the correct tsc options:

```sh
node_modules/execa/index.d.ts:6:8 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

6 } from './types/stdio/type';
         ~~~~~~~~~~~~~~~~~~~~
```

Neuter of the following combinations works
```
tsc  -t esnext -m esnext --module nodenext --moduleResolution nodenext
tsc  -t esnext -m esnext --module nodenext 
```

**Comment by ehmicky** [comment]
Hi @arlac77,

Thanks for reporting this. I am looking into this now.

Small note: `-m` and `--module` are the same CLI flag with `tsc`, so using `-m esnext --module nodenext` is probably an error.

**Comment by ehmicky** [comment]
This was fixed in `9.0.1`.
